### ISSUE TITLE
SFrame read_csv method parsing issue

### ISSUE THREAD

**Issue by canavandl** [graphlab-code/graphlab#172]
The SFrame "read_csv" method's "delimiter" argument is required to be a single character. The MovieLens dataset from http://grouplens.org/datasets/movielens/ (accessed on 1-11-15) uses a double-colon (::) as the delimiter, such that a row is of the form UserID::MovieID::Rating::Timestamp

The problem is movies with titles that contain a colon in the title, such as "Ace Ventura: When Nature Calls (1995)". Both single and double colons as delimiter arguments (the latter doesn't raise an exception or warning) fail to parse lines such as "19::Ace Ventura: When Nature Calls (1995)::Comedy".

Pandas allows for the use of greater-than-single-character separators and the dataset parses normally.

Using Graphlab-create 1.2.1

**Comment by znation** [comment]
Thanks for the issue @canavandl. This repository's issues are for PowerGraph, not GraphLab Create. I have ported the issue to our internal issue-tracking and we will look into it.

**Comment by canavandl** [comment]
Yes - I see that the repo was clearly labeled as such. Sorry about submitting to the wrong tracker and thanks for fixing it.
